#pragma config(Sensor, in1,    LightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  sonarSensor,    sensorSONAR_cm)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                 - Forward until Close Proximity -                                  *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*    In this program we make a while loop that will keep going while lights are on . We have         *|
|*    also the sonarSensor on so when it goes close to something the robot turns away and keeps       *|
|*    driving until it again gets to close to an object.                                              *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)                                                                                              *|
|*                                                                                                    *|
|*    2)                                                                                              *|
|*             *|
|*                                                                         *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor   - Port 2    rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor   - Port 3    leftMotor           VEX 3-wire module     Left side motor                   *|
|*    Digital - Port 9,10 sonarSensor         VEX Sonar Sensor      Front mounted, facing forward     *|
\*-----------------------------------------------------------------------------------------------4246-*/

#include "../functions/Drivefunctions.c";
bool lr = true;



void drive(){
	wait1Msec(2000);
	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder]  = 0;

	while(1 == 1)
	{
		if(SensorValue[rightEncoder] == SensorValue[leftEncoder])
		{

			motor[rightMotor] = 80;
			motor[leftMotor]  = 80;
		}
		else if(SensorValue[rightEncoder] > SensorValue[leftEncoder])

			motor[rightMotor] = 60;
			motor[leftMotor]  = 80;
		}
		else
		{

			motor[rightMotor] = 80;
			motor[leftMotor]  = 60;
		}
	}
}





//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{

	wait1Msec(2000);
	while(true){
	if(SensorValue(LightSensor) > 600){
		motor[rightMotor] = 0;
		motor[leftMotor] = 0;
	}
		else if(SensorValue(sonarSensor) > 20  || SensorValue(sonarSensor) == -1 )
		{
		motor[rightMotor] = 80;
		motor[leftMotor] = 80;
		}
		else{
		turn(127,true);
		resetEncoder();
		}
	}
}






//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
