#pragma config(Sensor, in1,    LightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  sonarSensor,    sensorSONAR_cm)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                 - Forward until Close Proximity -                                  *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*    In this program we make a while loop that will keep going while lights are on . We have         *|
|*    also the sonarSensor on so when it goes close to something the robot turns away and keeps       *|
|*    driving until it again gets to close to an object.                                              *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)                                                                                              *|
|*                                                                                                    *|
|*    2)                                                                                              *|
|*             *|
|*                                                                         *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor   - Port 2    rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor   - Port 3    leftMotor           VEX 3-wire module     Left side motor                   *|
|*    Digital - Port 9,10 sonarSensor         VEX Sonar Sensor      Front mounted, facing forward     *|
\*-----------------------------------------------------------------------------------------------4246-*/

#include "../functions/Drivefunctions.c";
bool lr = true;
task lights_off(){
	while(true){
	if(SensorValue(LightSensor) >600){
		StopAllTasks();

	}// if end

	} //while end
} //Task end

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{

	wait1Msec(2000);						// Robot waits for 2000 milliseconds before executing program
	StartTask(lights_off);
	while (true){

		while(SensorValue(sonarSensor) > 20  || SensorValue(sonarSensor) == -1 )		// Loop while robot's Ultrasonic sensor is further than 20 inches away from an object
		{                                                                         // || (or) it is '-1'.  (-1 is the value returned when nothing is in it's visable range)
			motor[rightMotor] = 63;			// Motor on port2 is run at half (63) power forward
			motor[leftMotor]  = 63;			// Motor on port3 is run at half (63) power forward
		}

		turn(127,true);
		resetEncoder();
	}




}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
