#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                 - ADVANCED Movement by Rotation -                                  *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program uses functions 'TurnLeft(float)' and 'Forward(float)' to very neatly and modularly   *|
|*  run your robot in a square.  There is a two second pause at the beginning of the program.         *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Reversing 'rightMotor' (port 2) in the "Motors and Sensors Setup" is needed with the        *|
|*        "Squarebot" model, but may not be needed for all robot configurations.                      *|
|*    2)  The values that you pass to the functions, 'Forward(float)' and 'TurnLeft(float)' are then  *|
|*        given to 'r' in each function.                                                              *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor   - Port 2    rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor   - Port 3    leftMotor           VEX 3-wire module     Left side motor                   *|
|*    Digital - Port 1,2  rightEncoder        VEX Quadrature enc.   Right side encoder                *|
|*    Digital - Port 3,4  leftEncoder         VEX Quadrature enc.   Left side encoder                 *|
\*-----------------------------------------------------------------------------------------------4246-*/
#include "../functions/Drivefunctions.c";
bool lr = true;
int nopower = 0;

// Functions Prototypes


// Declare Global Variables     /* 'rotations' will be a counter for every 360 encoder clicks */

int  dist = 429.5;


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
  wait1Msec(2000);        // Wait 2000 milliseconds before continuing.
  	for(int i=0; i<3; i++){

  		resetEncoder();
   		drive(dist,true);

   		resetEncoder();
    	turn(90,lr);
    	lr = false;
    	motor[rightMotor] = nopower;
	  	motor[leftMotor]  = nopower;
	  	wait1Msec(940);


  	}

  	resetEncoder();
    drive(dist,true);


}
